---
abstract: 'VM to write and run async code in usual sync-like way'
author:
  - 'Alex Efros  C<< <powerman-asdf@ya.ru> >>'
build_requires:
  AE: 0
  ExtUtils::MakeMaker: 6.59
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Async-Defer
no_index:
  directory:
    - inc
    - t
recommends:
  Pod::Coverage: 0.18
  Test::CheckManifest: 0.9
  Test::Perl::Critic: 0
  Test::Pod: 1.22
  Test::Pod::Coverage: 1.08
requires:
  Scalar::Util: 0
  perl: 5.12.0
  version: 0
resources:
  license: http://opensource.org/licenses/mit-license.php
version: 0.009004
